### ISSUE TITLE
Mojave builds are failing due to pyenv 1.2.12 issues

### ISSUE THREAD

**Issue by markosamuli** [markosamuli/macos-machine#12]
See https://github.com/markosamuli/ansible-pyenv/issues/16 for fix.

**Comment by markobynd** [comment]
Upgrading to [markosamuli.pyenv v2.0.0](https://github.com/markosamuli/ansible-pyenv/releases/tag/v2.0.0) uses Git for installing `pyenv` that fixes the installation issues.

**Comment by markosamuli** [comment]
The latest pyenv version in release v2.0.0 is working on macOS Mojave.
