### ISSUE TITLE
C tool SSLSCAN

### ISSUE THREAD

**Issue by carlosbyndldn** [markosamuli/macos-machine#18]
Add this to your repo:

- https://github.com/rbsec/sslscan

**Comment by markosamuli** [comment]
@carlosbyndldn Thanks for sending this to me.

Looking at the [changelog] and [TLSv1.3 and the future of sslscan][future-of-sslscan] section in the README file, doesn't feel like this tool is going to be maintained in the future, so I'm not going to add this to my standard setup.

> As such, sslscan should be considered legacy. I will still maintain it as far as I have time, but it is unlikely to ever support TLSv1.3, unless an OpenSSL fork is created by someone else that supports this while maintaining the insecure crypto that sslscan requires to be useful.

[changelog]: https://github.com/rbsec/sslscan/blob/1.11.13-rbsec/Changelog
[future-of-sslscan]: https://github.com/rbsec/sslscan#tlsv13-and-the-future-of-sslscan
